import { chromium } from 'playwright';
import { readFileSync, writeFileSync } from 'node:fs';
const html = readFileSync('poster/poster.html', 'utf8');
writeFileSync('poster/.out.html', html);
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const p = await b.newPage({ viewport: { width: 1400, height: 900 } });
await p.goto(`file://${process.cwd()}/poster/.out.html`);
await p.waitForTimeout(2800);
await p.pdf({ path: 'Nura-poster.pdf', width: '1400px', height: '900px', printBackground: true, pageRanges: '1' });
await p.screenshot({ path: 'Nura-poster.png' });
await b.close();
console.log('poster built');
